server:
  port: 8080

# add database properties

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
